name: Example GitHub Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:  ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: af-south-1
    
      - name: Get secrets from AWS Secrets Manager
        id: secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
             GALAXY, prod/GalaxyMatch
          parse-json-secrets: true
             

      - name: Echo secrets to terminal
        run: |
            echo "${{ env.GALAXY }}"
            
      - name: Echo the secrets
        run: |
          echo "Username is: ${{ env.GALAXY_USERNAME }}"
          echo "Password is: ${{ env.GALAXY_PASSWORD }}"
          echo "Database Engine is: ${{ env.GALAXY_ENGINE }}"
          echo "Host is: ${{ env.GALAXY_HOST }}"
          echo "Port is: ${{ env.GALAXY_PORT }}"
          echo "DB Instance Identifier is: ${{ env.GALAXY_DBINSTANCEIDENTIFIER }}"
          
          
      - name: Debug GALAXY_USERNAME (encoded)
        run: |
          echo "Base64: $(echo "${{  env.GALAXY_DBINSTANCEIDENTIFIER }}" | base64)"
          echo "Cg==" | base64 --decode

        

