name: Example GitHub Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:  ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: af-south-1
    
      - name: Get secrets from AWS Secrets Manager
        id: secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
             GALAXY, prod/GalaxyMatch
          parse-json-secrets: true
             

      - name: Echo secrets to terminal
        run: |
            echo "${{ env.GALAXY }}"
            
      - name: Echo the values
        run: |
          echo "Username is: ${{env.GALAXY_USERNAME}}"
          echo "Password is: $PASSWORD"
          echo "Google Client ID: $GOOGLECLIENTID"
          echo "Google Client Secret: $GOOGLECLIENTSECRET"
          
      - name: Echo using env block
        run: | 
          echo "From env: $USERNAME"
        env:
          USERNAME: ${{ env.GALAXY_USERNAME }}
        

